name: Cultivation
author: Sefiraat, J3fftw, JustAHuman
description: A Spiritual Successor to ExoticGarden
main: dev.sefiraat.cultivation.Cultivation
website: https://github.com/Sefiraat/Cultivation
version: ${project.version}
api-version: 1.19
depend:
  - Slimefun
commands:
  cultivation:
    description: /cultivation
    usage: /cultivation <sub>
permissions:
  cultivation.*:
    description: Provides permissions for all Cultivation functions
    default: op
    children:
      cultivation.admin: true
  cultivation.admin:
    description: Provides access to all Cultivation admin functions
    default: op
    children:
      cultivation.admin.entities: true
      cultivation.admin.modify_stat: true
      cultivation.admin.modify_analyzed: true
      cultivation.admin.structures: true
  cultivation.admin.entities:
    description: Allows the user to manage Cultivation Entities
    default: op
  cultivation.admin.modify_stat:
    description: Allows the user to modify plant stats
    default: op
  cultivation.admin.modify_analyzed:
    description: Allows the user to modify plant analyzed status
    default: op
  cultivation.admin.structures:
    description: Allows the user to manage Cultivation Structures
    default: op