name: Java CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 16
          cache: 'maven'
      - name: Build with Maven
        run: mvn package --file pom.xml

      - name: Upload to Blob Builds
        uses: WalshyDev/blob-builds/gh-action@main
        with:
          project: Cultivation
          apiToken: ${{ secrets.BLOB_BUILDS_API_TOKEN }}
          file: ./target/Cultivation.jar
          releaseNotes: ${{ github.event.head_commit.message }}